language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
# deploy:
#  provider: releases
#  api_key:
#    secure: "Vt2XPsdv7W0pGBT58ijcrI+Y99KC7gzVTj2ETjdzmgoKJuHNwjFozjLb/h/go+Rly3tTPrdpiBFEcJOVfg8xIRgFyV6HRw5KJGe6JwZ6SscB2UrE+C3+YYHfIqDlTkRXKsWIIdHKJre6LFRkuUK4k/5hUMEA9dY/oxbzpC9G+P3Pinygv2ycatSfzrhr+DGdcxekjN7MjqbYK+SkpLN76QTtICq8DmGaDCmJjbk+JuhhMu3ik2LeF8+/piTm0diCmcC9wr1wUGiO8Heuf0oWNSeLEJpjjN8SmEfaNFBLHKE9Ui6tBlMBA9agZtJr5+rDdBxswbIKs0MMuKT5bh59pS5RbkBgslr+LieDH6OW6lo7hFupqB8jOpLs8/aROevv/rRpv/79TR2lVlH9VBTh2hpPQiL8/ui/lBCOHZ99j6UHoUqlXtp7YV8ruBYxpqhQKjsM9QUxiThHc8BXCujcbwS4OwqavXdTt4sDGKc4DTB6hhnTJrnS5I5ASn3OITHk0XJ+zCru4ijQcHvhOSVG5y0hPYFUhXJvtMr9N1FTXvm8UcD4gNVixVUexGQq8uvoI8WKDZwAL4NfdqZFP/UItU+DG0kZesVK2PE3fIdoWMxRdPi0uoWg6uvwYuwwXejR6FOTdCm2abNGxlaC6zKdL7IzAI3N5LmdbSnCxHTUbBg="
#  file: "target/release/grrs"
#  skip_cleanup: true
#   on:
#     tags: true
